spring.application.name=server

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Animap
spring.datasource.username=postgres
spring.datasource.password=3535

# JPA (Hibernate) Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# all endpoints start with /animap
server.servlet.context-path=/animap


